// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6wmwkal21eh6dVZ0iH8Z2qtPxTsN5x8',
    appId: '1:534553427343:web:670d87ab1c03b2c7595ffa',
    messagingSenderId: '534553427343',
    projectId: 'chat-bot-b117f',
    authDomain: 'chat-bot-b117f.firebaseapp.com',
    storageBucket: 'chat-bot-b117f.firebasestorage.app',
    measurementId: 'G-Q0M2G5CP9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLhSdBNoIEyk0dg9lGPfIMoITnuIBZdCk',
    appId: '1:534553427343:android:74b2df2b08a950fe595ffa',
    messagingSenderId: '534553427343',
    projectId: 'chat-bot-b117f',
    storageBucket: 'chat-bot-b117f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4LKZyuYU6rahQvPujQ_0PmRGN7b7-bU',
    appId: '1:534553427343:ios:bc9a7af14b0540c1595ffa',
    messagingSenderId: '534553427343',
    projectId: 'chat-bot-b117f',
    storageBucket: 'chat-bot-b117f.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf4LKZyuYU6rahQvPujQ_0PmRGN7b7-bU',
    appId: '1:534553427343:ios:bc9a7af14b0540c1595ffa',
    messagingSenderId: '534553427343',
    projectId: 'chat-bot-b117f',
    storageBucket: 'chat-bot-b117f.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ6wmwkal21eh6dVZ0iH8Z2qtPxTsN5x8',
    appId: '1:534553427343:web:b7ac9515f24263fd595ffa',
    messagingSenderId: '534553427343',
    projectId: 'chat-bot-b117f',
    authDomain: 'chat-bot-b117f.firebaseapp.com',
    storageBucket: 'chat-bot-b117f.firebasestorage.app',
    measurementId: 'G-KKTG6DE25C',
  );
}
